language: python


install:
  - "pip install pytest"
  - "pip install -r requirements.txt"


script:
  - pytest 
  
deploy:
  provider: heroku
  api_key:
    secure: KEY
  app: app-btn-demo
  on:
    repo: fabiandzp/btn-app-demo
